# Makefile.in generated by automake 1.15 from Makefile.am.
# samtools/Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994-2014 Free Software Foundation, Inc.

# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.






am__is_gnu_make = { \
  if test -z '$(MAKELEVEL)'; then \
    false; \
  elif test -n '$(MAKE_HOST)'; then \
    true; \
  elif test -n '$(MAKE_VERSION)' && test -n '$(CURDIR)'; then \
    true; \
  else \
    false; \
  fi; \
}
am__make_running_with_option = \
  case $${target_option-} in \
      ?) ;; \
      *) echo "am__make_running_with_option: internal error: invalid" \
              "target option '$${target_option-}' specified" >&2; \
         exit 1;; \
  esac; \
  has_opt=no; \
  sane_makeflags=$$MAKEFLAGS; \
  if $(am__is_gnu_make); then \
    sane_makeflags=$$MFLAGS; \
  else \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        bs=\\; \
        sane_makeflags=`printf '%s\n' "$$MAKEFLAGS" \
          | sed "s/$$bs$$bs[$$bs $$bs	]*//g"`;; \
    esac; \
  fi; \
  skip_next=no; \
  strip_trailopt () \
  { \
    flg=`printf '%s\n' "$$flg" | sed "s/$$1.*$$//"`; \
  }; \
  for flg in $$sane_makeflags; do \
    test $$skip_next = yes && { skip_next=no; continue; }; \
    case $$flg in \
      *=*|--*) continue;; \
        -*I) strip_trailopt 'I'; skip_next=yes;; \
      -*I?*) strip_trailopt 'I';; \
        -*O) strip_trailopt 'O'; skip_next=yes;; \
      -*O?*) strip_trailopt 'O';; \
        -*l) strip_trailopt 'l'; skip_next=yes;; \
      -*l?*) strip_trailopt 'l';; \
      -[dEDm]) skip_next=yes;; \
      -[JT]) skip_next=yes;; \
    esac; \
    case $$flg in \
      *$$target_option*) has_opt=yes; break;; \
    esac; \
  done; \
  test $$has_opt = yes
am__make_dryrun = (target_option=n; $(am__make_running_with_option))
am__make_keepgoing = (target_option=k; $(am__make_running_with_option))
pkgdatadir = $(datadir)/global
pkgincludedir = $(includedir)/global
pkglibdir = $(libdir)/global
pkglibexecdir = $(libexecdir)/global
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = x86_64-unknown-linux-gnu
host_triplet = x86_64-unknown-linux-gnu
bin_PROGRAMS = samtools$(EXEEXT)
subdir = samtools
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ax_openmp.m4 \
	$(top_srcdir)/m4/boost.m4 $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/m4/m4-ax_perl_ext.m4 \
	$(top_srcdir)/m4/m4-ax_pkg_swig.m4 \
	$(top_srcdir)/m4/m4-ax_swig_enable_cxx.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
DIST_COMMON = $(srcdir)/Makefile.am $(bcftools_include_HEADERS) \
	$(library_include_HEADERS) $(am__DIST_COMMON)
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = $(top_builddir)/config.h
CONFIG_CLEAN_FILES =
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" \
	"$(DESTDIR)$(bcftools_includedir)" \
	"$(DESTDIR)$(library_includedir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
bcftools_libbcf_la_LIBADD =
am__dirstamp = $(am__leading_dot)dirstamp
am_bcftools_libbcf_la_OBJECTS = bcftools/bcf.lo bcftools/vcf.lo \
	bcftools/bcfutils.lo bcftools/prob1.lo bcftools/em.lo \
	bcftools/kfunc.lo bcftools/kmin.lo bcftools/index.lo \
	bcftools/fet.lo bcftools/mut.lo bcftools/bcf2qcall.lo \
	bcftools/call1.lo
bcftools_libbcf_la_OBJECTS = $(am_bcftools_libbcf_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
am__v_lt_1 = 
libbam_la_LIBADD =
am_libbam_la_OBJECTS = bgzf.lo kstring.lo bam_aux.lo bam.lo \
	bam_import.lo sam.lo bam_index.lo bam_pileup.lo bam_lpileup.lo \
	bam_md.lo razf.lo faidx.lo bedidx.lo knetfile.lo bam_sort.lo \
	sam_header.lo bam_reheader.lo kprobaln.lo bam_cat.lo
libbam_la_OBJECTS = $(am_libbam_la_OBJECTS)
PROGRAMS = $(bin_PROGRAMS)
am_samtools_OBJECTS = bam_tview.$(OBJEXT) bam_plcmd.$(OBJEXT) \
	sam_view.$(OBJEXT) bam_rmdup.$(OBJEXT) bam_rmdupse.$(OBJEXT) \
	bam_mate.$(OBJEXT) bam_stat.$(OBJEXT) bam_color.$(OBJEXT) \
	bamtk.$(OBJEXT) kaln.$(OBJEXT) bam2bcf.$(OBJEXT) \
	bam2bcf_indel.$(OBJEXT) errmod.$(OBJEXT) sample.$(OBJEXT) \
	cut_target.$(OBJEXT) phase.$(OBJEXT) bam2depth.$(OBJEXT) \
	padding.$(OBJEXT) bedcov.$(OBJEXT) bamshuf.$(OBJEXT) \
	bam_tview_curses.$(OBJEXT) bam_tview_html.$(OBJEXT)
samtools_OBJECTS = $(am_samtools_OBJECTS)
am__DEPENDENCIES_1 =
samtools_DEPENDENCIES = $(am__DEPENDENCIES_1) libbam.la \
	bcftools/libbcf.la
AM_V_P = $(am__v_P_$(V))
am__v_P_ = $(am__v_P_$(AM_DEFAULT_VERBOSITY))
am__v_P_0 = false
am__v_P_1 = :
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN     " $@;
am__v_GEN_1 = 
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
am__v_at_1 = 
DEFAULT_INCLUDES = -I. -I$(top_builddir)
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC      " $@;
am__v_CC_1 = 
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD    " $@;
am__v_CCLD_1 = 
SOURCES = $(bcftools_libbcf_la_SOURCES) $(libbam_la_SOURCES) \
	$(samtools_SOURCES)
DIST_SOURCES = $(bcftools_libbcf_la_SOURCES) $(libbam_la_SOURCES) \
	$(samtools_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
HEADERS = $(bcftools_include_HEADERS) $(library_include_HEADERS)
am__tagged_files = $(HEADERS) $(SOURCES) $(TAGS_FILES) $(LISP)
# Read a list of newline-separated strings from the standard input,
# and print each of them once, without duplicates.  Input order is
# *not* preserved.
am__uniquify_input = $(AWK) '\
  BEGIN { nonempty = 0; } \
  { items[$$0] = 1; nonempty = 1; } \
  END { if (nonempty) { for (i in items) print i; }; } \
'
# Make sure the list of sources is unique.  This is necessary because,
# e.g., the same source file might be shared among _SOURCES variables
# for different programs/libraries.
am__define_uniq_tagged_files = \
  list='$(am__tagged_files)'; \
  unique=`for i in $$list; do \
    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
  done | $(am__uniquify_input)`
ETAGS = etags
CTAGS = ctags
am__DIST_COMMON = $(srcdir)/Makefile.in $(top_srcdir)/depcomp AUTHORS \
	COPYING INSTALL NEWS
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
ACLOCAL = ${SHELL} /genome2/raid/alekseyz/MaSuRCA/missing aclocal-1.15
ALL_CXXFLAGS = 
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 0
AR = ar
AUTOCONF = ${SHELL} /genome2/raid/alekseyz/MaSuRCA/missing autoconf
AUTOHEADER = ${SHELL} /genome2/raid/alekseyz/MaSuRCA/missing autoheader
AUTOMAKE = ${SHELL} /genome2/raid/alekseyz/MaSuRCA/missing automake-1.15
AWK = gawk
BOOST_CPPFLAGS = -I/software/Linux64/include
BOOST_ROOT = /software/Linux64/include
CC = gcc
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -E
CPPFLAGS = 
CURSES_LIB = 0
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -DNDEBUG -std=c++0x -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DISTCHECK_CONFIGURE_FLAGS =  '--with-boost=/software/Linux64/include'
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /usr/bin/grep -E
EXEEXT = 
EXTRA_CXXFLAGS = -D_GLIBCXX_USE_NANOSLEEP -std=c++0x -fopenmp
FGREP = /usr/bin/grep -F
GREP = /usr/bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
JELLYFISH = $(bindir)/jellyfish
JELLYFISH2_0_CFLAGS = -I$(includedir)/jellyfish-1
JELLYFISH2_0_LIBS = -L$(libdir) -ljellyfish-2.0
LD = /usr/bin/ld -m elf_x86_64
LDFLAGS = 
LIBOBJS = 
LIBS = -lbz2 -lz -lrt -lpthread 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LOCAL_NAME = Linux-amd64
LTLIBOBJS = 
MACHINETYPE = amd64
MAKEINFO = ${SHELL} /genome2/raid/alekseyz/MaSuRCA/missing makeinfo
MANIFEST_TOOL = :
MAYBE_SWIG = swig
MKDIR_P = /usr/bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OSTYPE = Linux
OSVERSION = 3.8.2-genomegroup
OTOOL = 
OTOOL64 = 
PACKAGE = global
PACKAGE_BUGREPORT = gmarcais@umd.edu
PACKAGE_NAME = global
PACKAGE_STRING = global 1
PACKAGE_TARNAME = global
PACKAGE_URL = 
PACKAGE_VERSION = 1
PATH_SEPARATOR = :
PERL = /software/perl/bin/perl
PERL_EXT_CPPFLAGS = -D_REENTRANT -D_GNU_SOURCE -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include
PERL_EXT_INC = /software/perl/lib/5.10.1/x86_64-linux-thread-multi/CORE
PERL_EXT_LDFLAGS = -shared -O2 -L/usr/local/lib -fstack-protector
PERL_EXT_LIB = $(libdir)/perl
PERL_EXT_PREFIX = /software/perl
PKG_CONFIG = /usr/bin/pkg-config
PKG_CONFIG_LIBDIR = 
PKG_CONFIG_PATH = /software/Linux64/lib/pkgconfig
RANLIB = ranlib
SAMTOOLS_CFLAGS = -I$(includedir)/samtools
SAMTOOLS_LIBS = -L$(libdir) -lbam
SED = /usr/bin/sed
SET_MAKE = 
SHELL = /bin/sh
STRIP = strip
SWIG = 
SWIG_LIB = 
VALGRIND_CFLAGS = 
VALGRIND_LIBS = 
VERSION = 1
YAGGO = /software/ruby/bin/yaggo
abs_builddir = /genome2/raid/alekseyz/MaSuRCA/samtools
abs_srcdir = /genome2/raid/alekseyz/MaSuRCA/samtools
abs_top_builddir = /genome2/raid/alekseyz/MaSuRCA
abs_top_srcdir = /genome2/raid/alekseyz/MaSuRCA
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = x86_64-unknown-linux-gnu
build_alias = 
build_cpu = x86_64
build_os = linux-gnu
build_vendor = unknown
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = x86_64-unknown-linux-gnu
host_alias = 
host_cpu = x86_64
host_os = linux-gnu
host_vendor = unknown
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /genome2/raid/alekseyz/MaSuRCA/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = $(MKDIR_P)
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = ../
top_builddir = ..
top_srcdir = ..
ACLOCAL_AMFLAGS = -I m4
lib_LTLIBRARIES = libbam.la bcftools/libbcf.la
AM_CPPFLAGS = -I. -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -D_USE_KNETFILE -D_CURSES_LIB=0
AM_LDADD = -lm -lz -lpthread
library_includedir = $(includedir)/samtools
library_include_HEADERS = bam.h bam2bcf.h bam_endian.h bgzf.h		\
                          errmod.h faidx.h kaln.h khash.h klist.h	\
                          knetfile.h kprobaln.h kseq.h ksort.h		\
                          kstring.h razf.h sam.h sam_header.h		\
                          sample.h bam_tview.h

bcftools_includedir = $(library_includedir)/bcftools
bcftools_include_HEADERS = bcftools/bcf.h bcftools/kmin.h	\
                           bcftools/prob1.h

samtools_SOURCES = bam_tview.c bam_plcmd.c sam_view.c bam_rmdup.c	\
		   bam_rmdupse.c bam_mate.c bam_stat.c bam_color.c	\
		   bamtk.c kaln.c bam2bcf.c bam2bcf_indel.c errmod.c	\
		   sample.c cut_target.c phase.c bam2depth.c		\
		   padding.c bedcov.c bamshuf.c bam_tview_curses.c	\
		   bam_tview_html.c

samtools_LDADD = $(AM_LDADD) libbam.la bcftools/libbcf.la
libbam_la_SOURCES = bgzf.c kstring.c bam_aux.c bam.c bam_import.c	\
	            sam.c bam_index.c bam_pileup.c bam_lpileup.c	\
	            bam_md.c razf.c faidx.c bedidx.c knetfile.c		\
	            bam_sort.c sam_header.c bam_reheader.c kprobaln.c	\
	            bam_cat.c

bcftools_libbcf_la_SOURCES = bcftools/bcf.c bcftools/vcf.c		\
                             bcftools/bcfutils.c bcftools/prob1.c	\
                             bcftools/em.c bcftools/kfunc.c		\
                             bcftools/kmin.c bcftools/index.c		\
                             bcftools/fet.c bcftools/mut.c		\
                             bcftools/bcf2qcall.c bcftools/call1.c

all: all-am

.SUFFIXES:
.SUFFIXES: .c .lo .o .obj
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      ( cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh ) \
	        && { if test -f $@; then exit 0; else break; fi; }; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign samtools/Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign samtools/Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $(subdir)/$@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh

$(top_srcdir)/configure:  $(am__configure_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	cd $(top_builddir) && $(MAKE) $(AM_MAKEFLAGS) am--refresh
$(am__aclocal_m4_deps):

install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(libdir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(libdir)" || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; \
	locs=`for p in $$list; do echo $$p; done | \
	      sed 's|^[^/]*$$|.|; s|/[^/]*$$||; s|$$|/so_locations|' | \
	      sort -u`; \
	test -z "$$locs" || { \
	  echo rm -f $${locs}; \
	  rm -f $${locs}; \
	}
bcftools/$(am__dirstamp):
	@$(MKDIR_P) bcftools
	@: > bcftools/$(am__dirstamp)
bcftools/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) bcftools/$(DEPDIR)
	@: > bcftools/$(DEPDIR)/$(am__dirstamp)
bcftools/bcf.lo: bcftools/$(am__dirstamp) \
	bcftools/$(DEPDIR)/$(am__dirstamp)
bcftools/vcf.lo: bcftools/$(am__dirstamp) \
	bcftools/$(DEPDIR)/$(am__dirstamp)
bcftools/bcfutils.lo: bcftools/$(am__dirstamp) \
	bcftools/$(DEPDIR)/$(am__dirstamp)
bcftools/prob1.lo: bcftools/$(am__dirstamp) \
	bcftools/$(DEPDIR)/$(am__dirstamp)
bcftools/em.lo: bcftools/$(am__dirstamp) \
	bcftools/$(DEPDIR)/$(am__dirstamp)
bcftools/kfunc.lo: bcftools/$(am__dirstamp) \
	bcftools/$(DEPDIR)/$(am__dirstamp)
bcftools/kmin.lo: bcftools/$(am__dirstamp) \
	bcftools/$(DEPDIR)/$(am__dirstamp)
bcftools/index.lo: bcftools/$(am__dirstamp) \
	bcftools/$(DEPDIR)/$(am__dirstamp)
bcftools/fet.lo: bcftools/$(am__dirstamp) \
	bcftools/$(DEPDIR)/$(am__dirstamp)
bcftools/mut.lo: bcftools/$(am__dirstamp) \
	bcftools/$(DEPDIR)/$(am__dirstamp)
bcftools/bcf2qcall.lo: bcftools/$(am__dirstamp) \
	bcftools/$(DEPDIR)/$(am__dirstamp)
bcftools/call1.lo: bcftools/$(am__dirstamp) \
	bcftools/$(DEPDIR)/$(am__dirstamp)

bcftools/libbcf.la: $(bcftools_libbcf_la_OBJECTS) $(bcftools_libbcf_la_DEPENDENCIES) $(EXTRA_bcftools_libbcf_la_DEPENDENCIES) bcftools/$(am__dirstamp)
	$(AM_V_CCLD)$(LINK) -rpath $(libdir) $(bcftools_libbcf_la_OBJECTS) $(bcftools_libbcf_la_LIBADD) $(LIBS)

libbam.la: $(libbam_la_OBJECTS) $(libbam_la_DEPENDENCIES) $(EXTRA_libbam_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(LINK) -rpath $(libdir) $(libbam_la_OBJECTS) $(libbam_la_LIBADD) $(LIBS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p \
	 || test -f $$p1 \
	  ; then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' \
	    -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' \
	`; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list

samtools$(EXEEXT): $(samtools_OBJECTS) $(samtools_DEPENDENCIES) $(EXTRA_samtools_DEPENDENCIES) 
	@rm -f samtools$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(samtools_OBJECTS) $(samtools_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f bcftools/*.$(OBJEXT)
	-rm -f bcftools/*.lo

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/bam.Plo
include ./$(DEPDIR)/bam2bcf.Po
include ./$(DEPDIR)/bam2bcf_indel.Po
include ./$(DEPDIR)/bam2depth.Po
include ./$(DEPDIR)/bam_aux.Plo
include ./$(DEPDIR)/bam_cat.Plo
include ./$(DEPDIR)/bam_color.Po
include ./$(DEPDIR)/bam_import.Plo
include ./$(DEPDIR)/bam_index.Plo
include ./$(DEPDIR)/bam_lpileup.Plo
include ./$(DEPDIR)/bam_mate.Po
include ./$(DEPDIR)/bam_md.Plo
include ./$(DEPDIR)/bam_pileup.Plo
include ./$(DEPDIR)/bam_plcmd.Po
include ./$(DEPDIR)/bam_reheader.Plo
include ./$(DEPDIR)/bam_rmdup.Po
include ./$(DEPDIR)/bam_rmdupse.Po
include ./$(DEPDIR)/bam_sort.Plo
include ./$(DEPDIR)/bam_stat.Po
include ./$(DEPDIR)/bam_tview.Po
include ./$(DEPDIR)/bam_tview_curses.Po
include ./$(DEPDIR)/bam_tview_html.Po
include ./$(DEPDIR)/bamshuf.Po
include ./$(DEPDIR)/bamtk.Po
include ./$(DEPDIR)/bedcov.Po
include ./$(DEPDIR)/bedidx.Plo
include ./$(DEPDIR)/bgzf.Plo
include ./$(DEPDIR)/cut_target.Po
include ./$(DEPDIR)/errmod.Po
include ./$(DEPDIR)/faidx.Plo
include ./$(DEPDIR)/kaln.Po
include ./$(DEPDIR)/knetfile.Plo
include ./$(DEPDIR)/kprobaln.Plo
include ./$(DEPDIR)/kstring.Plo
include ./$(DEPDIR)/padding.Po
include ./$(DEPDIR)/phase.Po
include ./$(DEPDIR)/razf.Plo
include ./$(DEPDIR)/sam.Plo
include ./$(DEPDIR)/sam_header.Plo
include ./$(DEPDIR)/sam_view.Po
include ./$(DEPDIR)/sample.Po
include bcftools/$(DEPDIR)/bcf.Plo
include bcftools/$(DEPDIR)/bcf2qcall.Plo
include bcftools/$(DEPDIR)/bcfutils.Plo
include bcftools/$(DEPDIR)/call1.Plo
include bcftools/$(DEPDIR)/em.Plo
include bcftools/$(DEPDIR)/fet.Plo
include bcftools/$(DEPDIR)/index.Plo
include bcftools/$(DEPDIR)/kfunc.Plo
include bcftools/$(DEPDIR)/kmin.Plo
include bcftools/$(DEPDIR)/mut.Plo
include bcftools/$(DEPDIR)/prob1.Plo
include bcftools/$(DEPDIR)/vcf.Plo

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CC)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LTCOMPILE) -c -o $@ $<

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
	-rm -rf bcftools/.libs bcftools/_libs
install-bcftools_includeHEADERS: $(bcftools_include_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(bcftools_include_HEADERS)'; test -n "$(bcftools_includedir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bcftools_includedir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bcftools_includedir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_HEADER) $$files '$(DESTDIR)$(bcftools_includedir)'"; \
	  $(INSTALL_HEADER) $$files "$(DESTDIR)$(bcftools_includedir)" || exit $$?; \
	done

uninstall-bcftools_includeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(bcftools_include_HEADERS)'; test -n "$(bcftools_includedir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(bcftools_includedir)'; $(am__uninstall_files_from_dir)
install-library_includeHEADERS: $(library_include_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(library_include_HEADERS)'; test -n "$(library_includedir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(library_includedir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(library_includedir)" || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_HEADER) $$files '$(DESTDIR)$(library_includedir)'"; \
	  $(INSTALL_HEADER) $$files "$(DESTDIR)$(library_includedir)" || exit $$?; \
	done

uninstall-library_includeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(library_include_HEADERS)'; test -n "$(library_includedir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(library_includedir)'; $(am__uninstall_files_from_dir)

ID: $(am__tagged_files)
	$(am__define_uniq_tagged_files); mkid -fID $$unique
tags: tags-am
TAGS: tags

tags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	set x; \
	here=`pwd`; \
	$(am__define_uniq_tagged_files); \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: ctags-am

CTAGS: ctags
ctags-am: $(TAGS_DEPENDENCIES) $(am__tagged_files)
	$(am__define_uniq_tagged_files); \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"
cscopelist: cscopelist-am

cscopelist-am: $(am__tagged_files)
	list='$(am__tagged_files)'; \
	case "$(srcdir)" in \
	  [\\/]* | ?:[\\/]*) sdir="$(srcdir)" ;; \
	  *) sdir=$(subdir)/$(srcdir) ;; \
	esac; \
	for i in $$list; do \
	  if test -f "$$i"; then \
	    echo "$(subdir)/$$i"; \
	  else \
	    echo "$$sdir/$$i"; \
	  fi; \
	done >> $(top_builddir)/cscope.files

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

distdir: $(DISTFILES)
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
check-am: all-am
check: check-am
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(HEADERS)
install-binPROGRAMS: install-libLTLIBRARIES

installdirs:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" "$(DESTDIR)$(bcftools_includedir)" "$(DESTDIR)$(library_includedir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f bcftools/$(DEPDIR)/$(am__dirstamp)
	-rm -f bcftools/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool mostlyclean-am

distclean: distclean-am
	-rm -rf ./$(DEPDIR) bcftools/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-bcftools_includeHEADERS \
	install-library_includeHEADERS

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS install-libLTLIBRARIES

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man:

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -rf ./$(DEPDIR) bcftools/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-bcftools_includeHEADERS uninstall-binPROGRAMS \
	uninstall-libLTLIBRARIES uninstall-library_includeHEADERS

.MAKE: install-am install-strip

.PHONY: CTAGS GTAGS TAGS all all-am check check-am clean \
	clean-binPROGRAMS clean-generic clean-libLTLIBRARIES \
	clean-libtool cscopelist-am ctags ctags-am distclean \
	distclean-compile distclean-generic distclean-libtool \
	distclean-tags distdir dvi dvi-am html html-am info info-am \
	install install-am install-bcftools_includeHEADERS \
	install-binPROGRAMS install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am \
	install-libLTLIBRARIES install-library_includeHEADERS \
	install-man install-pdf install-pdf-am install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool pdf pdf-am ps ps-am tags tags-am uninstall \
	uninstall-am uninstall-bcftools_includeHEADERS \
	uninstall-binPROGRAMS uninstall-libLTLIBRARIES \
	uninstall-library_includeHEADERS

.PRECIOUS: Makefile


# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
